#! /usr/bin/env python3
'''
Each new term in the Fibonacci sequence is generated by adding the previous
two terms. By starting with 1 and 2, the first 10 terms will be:
   1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not
exceed four million, find the sum of the even-valued terms.
'''

num_A = 1
num_B = 1
counter = 0

while num_A < 4000000:
    if not num_A % 2:
        counter += num_A

    num_B += num_A
    num_A, num_B = num_B, num_A

print("R: %d" % counter)
